FROM logstash:7.7.0
USER root  
RUN mkdir /usr/share/logstash/outputs/ || true
RUN chown -R logstash:logstash /usr/share/logstash/outputs/
COPY --chown=logstash:logstash ./logstash.yml /usr/share/logstash/config/
COPY --chown=logstash:logstash ./logstash.conf /usr/share/logstash/pipeline/
