FROM elastic/filebeat:7.7.0
 
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
COPY test.log /usr/share/filebeat/test.log
USER root
RUN mkdir /usr/share/filebeat/dockerlogs
RUN chown -R root /usr/share/filebeat/
RUN chmod -R go-w /usr/share/filebeat/